### ISSUE TITLE
Not working on Debian

### ISSUE THREAD

**Issue by mredaelli** [guibou/nixGL#1]
After installing kitty and nixGL, I try runnig `nixGL kitty` on Debian buster, and I get

````
Traceback (most recent call last):
  File "/home/turing/.nix-profile/bin/nixGL", line 21, in <module>
    for line in subprocess.check_output(['ldd', realProg]).split(b'\n'):
  File "/nix/store/y95dd7cmw2xlf6hvg2j93b227pblpaaq-python3-3.6.4/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/nix/store/y95dd7cmw2xlf6hvg2j93b227pblpaaq-python3-3.6.4/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ldd', b'/home/turing/.nix-profile/bin/kitty']' returned non-zero exit status 1.
````

I'm veeeery new to nix, so forgive if there is something obvious :)

**Comment by guibou** [comment]
Thank you for repporting this issue.

Apparently "kitty" uses a wrapper script (i.e. `.nix-profile/bin/kitty` is a symlink to a bash script), and this is unfortunately incompatible with "nixGL". Unfortunately, wrapping the real kitty executable is also broken due to dynamic loading at runtime.

I'm afraid that "nixGL" will not work as is for "kitty" and I don't have any immediate idea to improve the situation.

**Comment by mredaelli** [comment]
Thanks!
Well, maybe it's a good excuse to try NixOS for real :P

**Comment by guibou** [comment]
Well,

Actually there are other solutions which may work for you:

- nix-vendor-gl (https://github.com/deepfire/nix-install-vendor-gl) of you
use an Nvidia driver
- A simple symlink if you use an intel (mesa) driver:

```
sudo ln -sf /nix/store/HASH-mesa-noglu-VERSION-drivers /run/opengl-driver
```

The symlink works really well if you can install the same version of
"mesa-noglu" as the one used by your host system.

Le lun. 8 janv. 2018 à 16:41, Massimo Redaelli <notifications@github.com> a
écrit :

**Comment by mredaelli** [comment]
Good to know!
For the moment I solved by compiling the program it myself, so no biggie, but will keep in mind. Thanks for your help!

**Comment by guibou** [comment]
You may be interested to know that I changed the way `nixGL` works and it now works smoothlessly with `kitty`. I lifted most of the limitation of the previous approach, this should now work reliably with most of the OpenGL applications.

**Comment by mredaelli** [comment]
Glad to hear! Although now I'm in NixOS itself (and hope to keep using it :P )
