### ISSUE TITLE
NixGL on arm64

### ISSUE THREAD

**Issue by itaysharir** [guibou/nixGL#109]
I have an M1 mac and i run fedora with nix installed on a VM. i want to install a WM but i requires me to install NixGL. Is there an arm64 version of NixGL? 
![Screen Shot 2022-08-09 at 15 34 07](https://user-images.githubusercontent.com/87126382/183648054-c23b0e36-8646-4a34-9baf-5a73e1b43137.jpg)

**Comment by guibou** [comment]
Hello,

Thank you for opening this issue.

I don't see any reason why nixGL wouldn't work on `arm64` as long as the OpenGL stack works on it. Except that the `flake.nix` file had never been written with this in mind.

I'll give it a shot right now.

**Comment by guibou** [comment]
Would you mind testing the branch `inclusive_nix_flake` please? You may try that using:

```
nix profile install github:guibou/nixGL/inclusive_nix_flake
```
