### ISSUE TITLE
problem with install trough flakes

### ISSUE THREAD

**Issue by brothermechanic** [guibou/nixGL#117]
Hello.
Thank you for repository!
Help me to install it trough flakes
This is an error
```
$ nix profile install github:guibou/nixGL#nixGLNvidia
error: attribute 'currentTime' missing

       at /nix/store/vadnrinka7qsa6qn69g98hgvybgh6g2v-source/nixGL.nix:216:18:

          215|           # Add an impure parameter to force the rebuild on each access.
          216|           time = builtins.currentTime;
             |                  ^
          217|           preferLocalBuild = true;
(use '--show-trace' to show detailed location information)
```

**Comment by guibou** [comment]
could you try with `nix build --impure github:guibou/nixGL#nixGLNvidia` ?

**Comment by ryanswrt** [comment]
Here's the line I use `NIXPKGS_ALLOW_UNFREE=1 nix profile install github:guibou/nixGL --impure` ; for some reason nix profile doesn't read my local nix conf to allow unfree flakes to be installed

**Comment by brothermechanic** [comment]
> could you try with `nix build --impure github:guibou/nixGL#nixGLNvidia` ?
that's builds fine
```
$ nix build --impure github:guibou/nixGL#nixGLNvidia
$ ls result/bin/nixGLNvidia-515.65.01
```

**Comment by brothermechanic** [comment]
> Here's the line I use `NIXPKGS_ALLOW_UNFREE=1 nix profile install github:guibou/nixGL --impure` ; for some reason nix profile doesn't read my local nix conf to allow unfree flakes to be installed
Works!
```
$ nix profile install github:guibou/nixGL#nixGLNvidia --impure
```
Thank you!

**Comment by brothermechanic** [comment]
For final understanding...

--impure
Allow access to mutable paths and repositories.

https://github.com/guibou/nixGL - is mutable repo?

**Comment by guibou** [comment]
@brothermechanic yes, the `nixGLNvidia` package does some impure stuffs in order to auto detect nvidia version.

**Comment by guibou** [comment]
I'm closing.

However, we should keep in mind that defining a solution to fix all theses impurity could be awesome.

**Comment by 0xdapper** [comment]
do we know how to fix this when using home-manager's `home.packages`?
