### ISSUE TITLE
Nvidia Tesla support

### ISSUE THREAD

**Issue by NinjaTrappeur** [guibou/nixGL#120]
The Nvidia tesla line is not supported by the `XFree86` proprietary dirver, it has a specific "data center" one: https://www.nvidia.fr/Download/driverResults.aspx/193507/en-us

If we want to support that card lineage, we'll probably want to find some heuristics to detect them in the auto detection script.

I don't have a good solution to propose for this issue, but I quickly hacked my way out of this with: https://github.com/NinjaTrappeur/nixGL/commit/487f718e0ce01879dc531af2179c623486570412. Ic could be useful for people hitting this same issue :). I only tested the GLX interface, the EGL one could be entirely broken with this patch.

Note: on the GLX side, it seems like xorg/libglvnd is getting confused by this card and assumes it's supposed to be driven by Mesa. You need to hint it to the right vendor name using `__GLX_VENDOR_LIBRARY_NAME`.

**Comment by KiruyaMomochi** [comment]
Is this #119?

**Comment by NinjaTrappeur** [comment]
Ah, indeed, it is! Let's copy this message there.

**Comment by NinjaTrappeur** [comment]
Duplicate of #119

**Comment by zmenciso** [comment]
@picnoir Thanks for discovering this.  I'm using RHEL8 with `nvidia-driver:latest-dkms`, which is `545.23.08`.  For some reason, NVIDIA doesn't have anything close to this up-to-date on their downloads page for Tesla--I'll have to dig into this more.

Either way, you've saved me a ton of troubleshooting time.
