### ISSUE TITLE
At least nixGLIntel does not work with older nixpkgs

### ISSUE THREAD

**Issue by Teekuningas** [guibou/nixGL#123]
Seems to have broken in the last pull request.. For me it has been important to be able to use older nixpkgs versions because some of the support for older graphics drivers gets dropped in the newer versions. I'm happy to pin versions of nixGL however, so this is more like a for-your-information.

```
❯ nix repl
Welcome to Nix 2.11.0. Type :? for help.

nix-repl> builtins.currentSystem
"x86_64-linux"
```

```
> nix shell --override-input nixpkgs nixpkgs/20.09 github:guibou/nixGL#nixGLIntel
warning: not writing modified lock file of flake 'github:guibou/nixGL':
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/441dc5d512153039f19ef198e662e4f3dbb9fd65' (2022-08-15)
  → 'github:NixOS/nixpkgs/cd63096d6d887d689543a0b97743d28995bc9bc3' (2020-10-27)
error: Package ‘intel-gmmlib-20.2.5’ in /nix/store/fw277i56nwladrnqzlswf4p4pakl2pmx-source/pkgs/development/libraries/intel-gmmlib/default.nix:21 is not supported on ‘i686-linux’, refusing to evaluate.

       a) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

This still works:
```
nix shell --override-input nixpkgs nixpkgs/nixos-20.09 github:guibou/nixGL/643e730efb981ffaf8478f441ec9b9aeea1c89f5#nixGLIntel
```

**Comment by SuperSandro2000** [comment]
You should be able to just ignore that. i686 worked all the time and enabling it was basically just changing meta.platforms. https://github.com/NixOS/nixpkgs/commit/c32fa3f108532b19b6482078dc10b99f752001f2

Also 20.09 is very old. If you need an older version of one package I would highly recommend overlays instead.

**Comment by guibou** [comment]
Thank you for letting us know.

Indeed, the problem of compatibility of nixGL is complex. I'm happy to know that you are ok with pinning. Please tell us if pinning a specific version of nixGL does not work for you in the future.

**Comment by Teekuningas** [comment]
Ok, thanks, fine enough!

-- Erkka

**Comment by SuperSandro2000** [comment]
I would suggest to follow the supported nixos releases to be able to push bug fixes into them if required.
