### ISSUE TITLE
Broken pipe on 530.30.02

### ISSUE THREAD

**Issue by Programmerino** [guibou/nixGL#126]
I'm getting the following error when trying to install `nixGLNvidia` using `nix profile install github:guibou/nixGL#nixGLNvidia --impure`:

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
tail: error writing 'standard output': Broken pipe
Creating directory NVIDIA-Linux-x86_64-530.30.02
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 530.30.02/nix/store/8zpy6cffgk57wb8vnpyas6c9x21bixmj-NVIDIA-Linux-x86_64-530.3>
tail: error writing 'standard output': Broken pipe
/nix/store/8zpy6cffgk57wb8vnpyas6c9x21bixmj-NVIDIA-Linux-x86_64-530.30.02.run: line 720: /dev/tty: No such device or address

Terminated
xz: (stdin): File format not recognized
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
tail: error writing 'standard output': Broken pipe
```

Any help or tips would be appreciated. I get similar errors when using the channel installation method, or from source.

**Comment by Programmerino** [comment]
Nevermind, this should be fixed when https://github.com/NixOS/nixpkgs/pull/218876 is merged (zstd needs to be added to the nativeBuildInputs)

**Comment by shackra** [comment]
please reopen this issue, https://github.com/NixOS/nixpkgs/pull/222762 is the new fix and isn-t merge yet
