### ISSUE TITLE
Doesn't work with nvidia version 415.13

### ISSUE THREAD

**Issue by jascase901** [guibou/nixGL#17]
./nvidiaInstall.py 415.13  nixGLNvidia
path is '/nix/store/mp5phz9a923hk9sxdf8iyg3p0i82dqmr-NVIDIA-Linux-x86_64-415.13.run'
these derivations will be built:
  /nix/store/calk0i31k1bdjdci2p9n6cr9bl18f1j2-nvidia-415.13.drv
  /nix/store/2k530a3vqspy4q5dww9nf1a2bjq0nazw-nixGLNvidia.drv
building '/nix/store/calk0i31k1bdjdci2p9n6cr9bl18f1j2-nvidia-415.13.drv'...
unpacking sources
Creating directory NVIDIA-Linux-x86_64-415.13
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 415.13.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
source root is NVIDIA-Linux-x86_64-415.13
setting SOURCE_DATE_EPOCH to timestamp 1541033469 of file NVIDIA-Linux-x86_64-415.13/nvidia-bug-report.sh
patching sources
configuring
no configure script, doing nothing
building
installing
cp: cannot stat '32/tls': No such file or directory
builder for '/nix/store/calk0i31k1bdjdci2p9n6cr9bl18f1j2-nvidia-415.13.drv' failed with exit code 1
cannot build derivation '/nix/store/2k530a3vqspy4q5dww9nf1a2bjq0nazw-nixGLNvidia.drv': 1 dependencies couldn't be built
error: build of '/nix/store/2k530a3vqspy4q5dww9nf1a2bjq0nazw-nixGLNvidia.drv' failed
Traceback (most recent call last):
  File "./nvidiaInstall.py", line 13, in <module>
    subprocess.check_call(["nix-build", "-A", tool, "--argstr", "nvidiaVersion", nvidiaVersion, "--argstr", "nvidiaHash", nvidiaHash])
  File "/nix/store/bwfygfcdvis9wd1c1v51xwnwhw1hx0a0-python3-3.6.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nix-build', '-A', 'nixGLNvidia', '--argstr', 'nvidiaVersion', '415.13', '--argstr', 'nvidiaHash', b'0nk4a45a93qc98gy5lkb14v7m837p0635kpynrr2mqa8p1vnvlia']' returned non-zero exit status 100.

**Comment by guibou** [comment]
Thank you for reporting that.

Apparently the nvidia driver package changed.

I'll try to find a way to make something reproducible (`nixGL` still needs to handle "old" drivers)

**Comment by jascase901** [comment]
Thank you. I ended up using 4.10 which worked brilliantly.

**Comment by jascase901** [comment]
nvidia 430.26 works as well.

**Comment by guibou** [comment]
Ok. Thank you. Sorry I gave no answer in the meantime.
