### ISSUE TITLE
Doesn't run on nix nixos-20.09

### ISSUE THREAD

**Issue by yakimant** [guibou/nixGL#183]
```
$ nix run --override-input nixpkgs nixpkgs/nixos-20.09 --impure github:nix-community/nixGL -- program
...
error: builder for '/nix/store/1nd00kp9fs6afpa3ylhb49ghy04jhbnr-intel-gmmlib-20.2.5.drv' failed with exit code 2;
       last 10 log lines:
       > [ 98%] Building CXX object Source/GmmLib/ULT/CMakeFiles/GMMULT.dir/GmmULT.cpp.o
       > cc1plus: warning: '-Werror=' argument '-Werror=implicit-function-declaration' is not valid for C++
       > [100%] Linking CXX executable GMMULT
       > [100%] Built target GMMULT
       > Scanning dependencies of target Run_ULT
       > running ULTs
       > Illegal instruction
       > make[2]: *** [Source/GmmLib/ULT/CMakeFiles/Run_ULT.dir/build.make:81: Run_ULT] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:190: Source/GmmLib/ULT/CMakeFiles/Run_ULT.dir/all] Error 2
       > make: *** [Makefile:171: all] Error 2
```

We need old nixpkgs with old `glibc` to run a program on old Linux distributions.

Probably `nixGL` worked before, will bisect.

**Comment by yakimant** [comment]
Related issue: https://github.com/nix-community/nixGL/issues/123

**Comment by yakimant** [comment]
This works:
https://github.com/nix-community/nixGL/commit/643e730efb981ffaf8478f441ec9b9aeea1c89f5

The next commit doesn't:
https://github.com/nix-community/nixGL/commit/cd2ec2116075abca891e90839d94840b26f28c5d

**Comment by SuperSandro2000** [comment]
NixOS 20.09 is EOL since years. You should probably update to a newer version.

**Comment by yakimant** [comment]
We need to use that one due to `glibc` compatibility.

**Comment by SuperSandro2000** [comment]
Then you probably want to upgrade your base distro.

nixGL is certainly not supporting a NixOS version that old.

**Comment by yakimant** [comment]
The thing is we want to build an app with old `glibc` so it can run on most distros.
Currently the oldest supported `Ubuntu LTS` is `20.04`, that's why we are stuck with building with `nixpkgs` `20.09`.
So people could run our app on `Ubuntu LTS 20.04`.

I was pretty sure you will not fix the issue. But still usefull to document the workaround.

Pinning https://github.com/nix-community/nixGL/commit/643e730efb981ffaf8478f441ec9b9aeea1c89f5 works with nixpkgs `20.09`.

You can close the issue.

**Comment by SuperSandro2000** [comment]
What you are doing is unsupported by NixOS upstream and inherently insecure as 20.09 didn't receive an security update in 3.5 years. There are probably many high targeted CVEs since then. You are putting your users at risk with such a prebuilt binary.

I also don't think we should document such an old nixpkgs version. People should not use it anymore.

PS I can't close issues here.

**Comment by yakimant** [comment]
That's a good point, thank you!
So it will be compatibility vs security.
