### ISSUE TITLE
Could this work for fake a desktop profile en gles arm platforms under mesa drivers?

### ISSUE THREAD

**Issue by Askmewho** [guibou/nixGL#20]
Thats all.

**Comment by guibou** [comment]
I have no idea. Could you give me a bit more details about what you are trying to do?

**Comment by Askmewho** [comment]
There are a lot of "arm" gous than has his mesa driver well developed. But some of that drivers doesnt want to add third generation opengl desktop profile (they add 2.1 but doesnt want to do some hacking to add 3.x). Some games should run with the actual gl instructions on 3.x gl ES, and maybe this project could help on fake it.

**Comment by guibou** [comment]
@Askmewho Does that mean that the issue is fixed for you?

**Comment by Askmewho** [comment]
That means I found a repo than already do what I need (at least on theory). I do t have the gles profile needed to test it anyway. Rpi4 videocore6 gpu has a mesa profile of gles 3.0, but its gles 3.2 capable on the hardware, so, not ready to try to fage my profile! Thanks to ask
