### ISSUE TITLE
nixGLNvidia: 5: $@: not found

### ISSUE THREAD

**Issue by andregrigon** [guibou/nixGL#22]
After commit 5ba3174 I get the error "$@: not found" when running nixGLNvidia with or without arguments. The script looks like this:

    #!/usr/bin/env sh
    
    
    export LD_LIBRARY_PATH=/nix/store/sinkyq6agjlpqg2vmmdfzncfnqnhx9cz-libglvnd-1.2.0/lib:/nix/store/29dnq9ca04jlkax8x272al17lm2nfpmi-nvidia-435.21/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    "\$@"

Notice the last line, which before 5ba3174 was just `"$@"`.

I think the problem is with the non-expanding here-doc `'FOO'` instead of `FOO` in line 62 of default.nix, which @expipiplus1 mentioned in #21 . It seems to affect the escaping rules.

**Comment by guibou** [comment]
Thank you for reporting that.

@expipiplus1 could you have a look?

**Comment by guibou** [comment]
Closed by #23

**Comment by expipiplus1** [comment]
oops! sorry. Thanks for fixing @guibou
