### ISSUE TITLE
Provide version of a wrapper with libGLX_indirect.so.0 (?)

### ISSUE THREAD

**Issue by allter** [guibou/nixGL#24]
On my notebook I had to patch nixGLIntel as the following to work:
```
--- a/default.nix
+++ b/default.nix
@@ -86,11 +86,13 @@ rec {
          homepage = "https://github.com/guibou/nixGL";
      };
     } ''
+      mkdir -p $out/lib
+      ln -s ${mesa_drivers}/lib/libGLX_mesa.so.0 $out/lib/libGLX_indirect.so.0
       mkdir -p $out/bin
       cat > $out/bin/nixGLIntel << FOO
       #!/usr/bin/env sh
       export LIBGL_DRIVERS_PATH=${mesa_drivers}/lib/dri
-      export LD_LIBRARY_PATH=${mesa_drivers}/lib:\$LD_LIBRARY_PATH
+      export LD_LIBRARY_PATH=${mesa_drivers}/lib:$out/lib:\$LD_LIBRARY_PATH
       "\$@"
       FOO
```
This is based on reading of https://github.com/NixOS/nixpkgs/issues/9415 .
I don't know the linux OpenGL stack enough to understand why. :)

**Comment by guibou** [comment]
@allter 

Thank you.

Could you first try the `master` version of `nixGL`. I've done changes yesterday and they may have some impact.

If it does not fix your issue, please, can you tell me what precise command you run so I can reproduce the bug?

**Comment by allter** [comment]
> Could you first try the `master` version of `nixGL`. I've done changes yesterday and they may have some impact.

master doesn't work for me because i don't have invidia:
```
$ nix-env --file ./ -i nixGLIntel
error: cannot coerce null to a string, at /home/allter/.dotfiles/.config/nixpkgs/nixGLmaster/default.nix:14:21
```

**Comment by allter** [comment]
> If it does not fix your issue, please, can you tell me what precise command you run so I can reproduce the bug?

If this can help, i send here output of nixGLIntel glxinfo (with nixGLIntel patched from 5ba3174 as above):
[glxinfo.nix.txt](https://github.com/guibou/nixGL/files/4291352/glxinfo.nix.txt)

output of ubuntu's system glxinfo:
[glxinfo.ubuntu.txt](https://github.com/guibou/nixGL/files/4291354/glxinfo.ubuntu.txt)

lshw:
[lshw.txt](https://github.com/guibou/nixGL/files/4291355/lshw.txt)

**Comment by guibou** [comment]
@allter (sorry, I edited your comment by mistake).

> `nix-env --file ./ -i nixGLIntel`

It is `nix-env --file ./ -i -A nixGLIntel`.

Could you retry `master` using this correct command?

**Comment by guibou** [comment]
@allter without much informations, I'm closing this bug. Feel free to reopen if you still have problem.

**Comment by zakame** [comment]
I ran into this very same issue while evaluating Alacritty and Kitty on Nix under Slackware 14.2, and I adapted this change from @allter to the latest `master` version to make these terminals work on my Intel i915-based laptop.  Let me open a PR in a little bit...
