### ISSUE TITLE
add nvidiaFile option in addition to nvidiaVersion

### ISSUE THREAD

**Issue by koddo** [guibou/nixGL#49]
Hello. I tried installing nixGL on my system and the driver file is missing on the nvidia website:

```
$ nix-env -f ./ -iA nixGLNvidia
building '/nix/store/7zf3gyg71xrap7564bp27nakl8sx8v44-impure-nvidia-version-file.drv'...
installing 'nixGLNvidia-440.33'
error: unable to download 'http://download.nvidia.com/XFree86/Linux-x86_64/440.33/NVIDIA-Linux-x86_64-440.33.run': HTTP error 404
```

That's funny because the driver is not that old and they deleted it already. I upgraded it using ubuntu's utilities and nixGL got installed successfully.

Would be great to have an option to host this file independently for reproducibility.

**Comment by guibou** [comment]
Never trust proprietary company for reproducibility.

Did you see that you can pass `nvidiaHash` as well when building. This way, if your driver is already in the nix store, it will be picked from the nix store.

You can use `nix-prefetch-url` to download it and add it to the store (and get its control sum). `nix-prefetch-url` also accepts a local file path, such as `nix-prefetch-url file:///abs/path/to/file.run`.

Is this workflow fine for you?

**Comment by koddo** [comment]
Yeah, looks good, thanks.
