### ISSUE TITLE
Typo in file?

### ISSUE THREAD

**Issue by yilinwei** [guibou/nixGL#58]
I'm using vulkan so I haven't tested it, but this looks like it might be a typo?

https://github.com/guibou/nixGL/blob/e7039bfb2c250f2259955901753562d170d6ea14/nixGL.nix#L183

**Comment by zicklag** [comment]
I mean, it's working for me on OpenGL, but that sure does look like a typo. :man_shrugging: :smile:

**Comment by guibou** [comment]
That's definitly a typo. And the funny part is that it is not an issue because `nixGL` is "manually" linked inside the executed code.

Thank you. I'll fix that soon, but that's not causing any bug.
