### ISSUE TITLE
error:nvidia340 missing file*

### ISSUE THREAD

**Issue by Kampouse** [guibou/nixGL#65]
installing
sed: can't read 10_nvidia.json: No such file or directory
builder for '/nix/store/2rf3b7fl9w3ccy3gra46jpg5wvg5pcrr-nvidia-340.108.drv' failed with exit code 2
cannot build derivation '/nix/store/h59yvaaqk78diplzrm60d0jkvmdcmdr2-nixVulkanNvidia-340.108.drv': 1 dependencies couldn't be built
error: build of '/nix/store/h59yvaaqk78diplzrm60d0jkvmdcmdr2-nixVulkanNvidia-340.108.drv' failed

>

**Comment by guibou** [comment]
Hello,

Could you give me a bit more context on how this happened?

**Comment by Kampouse** [comment]
my current computer that run nixos as hardtime using  openGL i came here to see if this module would be able to resolve the issue but when trying to the script i end up with the error cited here
