### ISSUE TITLE
Installing nixGLDefault can be done by adding this repo as a channel

### ISSUE THREAD

**Issue by Thesola10** [guibou/nixGL#68]
Here's a suggestion for a "quick start" install:

```sh
nix-channel --add https://github.com/guibou/nixGL/archive/master.tar.gz nixgl && nix-channel --update
nix-env -iA nixgl.nixGLDefault
```
Running the commands above has the added benefit of following the system upgrade process, and is inspired by home-manager's install process.

**Comment by guibou** [comment]
Awesome idea. Thank you.

I'll try to update the Readme.

**Comment by samuela** [comment]
I'm not 100% up-to-date on what the recommended approaches are but alternative solutions also include flakes and overlays. I believe nix-channels are considered to be on the way out (slowly).

**Comment by samuela** [comment]
I just tried this process, and install worked just fine... I was able to run `nix-env -iA nixgl.nixGLDefault`. But now `nixGLDefault` doesn't seem to exist:
```
> nixGLDefault
zsh: command not found: nixGLDefault
```
OTOH it does seem to work if with `nixGLNvidia`.

**Comment by samuela** [comment]
> I think the binary created by nixGLDefault is just nixGL, which exists on my machine

Oh, I see... I think this might be worth clarifying in the README then. I'd be happy to take a stab at it

**Comment by edrex** [comment]
I'm a new user, and I went the nixUnstable/flakes route from the beginning. AFAIK nixUnstable doesn't support channels:

```
~ ❯ nix-env -iA nixgl.nixGLIntel 
error: profile '/nix/var/nix/profiles/per-user/eric/profile' is incompatible with 'nix-env';
please use 'nix profile' instead
```

Some option needs to be provided for end users using `nixFlakes`/`nixUnstable`. Continuing over on https://github.com/guibou/nixGL/issues/16

**Comment by gerardbosch** [comment]
Hi @edrex, I'm in the same situation than you and getting the same error. Did you figure out how to install `nixGL` with 'nix profile'? Thx!

**Comment by guibou** [comment]
The problem you are having is because you upgraded your environment to flake. `nix-env` does not work anymore.

I'm not using flakes so I'm afraid I have no idea on how to solve that, of course #16 is a good entrypoint.
