### ISSUE TITLE
Adding nixGL channel appears to break nix-env

### ISSUE THREAD

**Issue by jkatzmewing** [guibou/nixGL#72]
With a fresh install of nix, on a Surface Pro 3 with Intel graphics:

```
% nix-channel --add https://github.com/guibou/nixGL/archive/master.tar.gz nixgl && nix-channel --update
these derivations will be built:
  /nix/store/i72062fyqn1rkxxi0cmly4avw64bnzn7-nixgl.drv
building '/nix/store/i72062fyqn1rkxxi0cmly4avw64bnzn7-nixgl.drv'...
unpacking channels...
created 2 symlinks in user environment
% nix-env -qaP 'nixgl.*'
error: cannot read '/nix/store/28iv2fl40sf87d1wa9wf0v8vvkl0qffi-impure-nvidia-version-file', since path '/nix/store/63z4g82j6r1dhkcad6c6dii8qh0l7h7x-impure-nvidia-version-file.drv' is not valid, at /nix/store/q1zl5sdbrxk27msdlaj9win0fiyyrr1j-nixgl/nixgl/nixGL.nix:48:16
% nix-env -qa 'nixgl.*' 
error: cannot read '/nix/store/ikgz0x0blhnfhh5r3js5lp8i2mcax19q-impure-nvidia-version-file', since path '/nix/store/vybadp8vb5lhmwds6vgscfyvarz0l47x-impure-nvidia-version-file.drv' is not valid, at /nix/store/q1zl5sdbrxk27msdlaj9win0fiyyrr1j-nixgl/nixgl/nixGL.nix:48:16
```

Edit: update is also broken.

```
% nix-env -u
building '/nix/store/vf8kdxp1dxqak6vp0v1rfg5lfd3jppxf-impure-nvidia-version-file.drv'...
cp: cannot stat '/proc/driver/nvidia/version': No such file or directory
error: cannot coerce null to a string, at /nix/store/q1zl5sdbrxk27msdlaj9win0fiyyrr1j-nixgl/nixgl/nixGL.nix:57:29
(use '--show-trace' to show detailed location information)
```

**Comment by jkatzmewing** [comment]
Specifying the attribute path works at least:

```
% nix-env -q -A nixpkgs -abP 'chromium.*'
nixpkgs.chromium               chromium-91.0.4472.77
nixpkgs.chromium-bsu           chromium-bsu-0.9.16.1
nixpkgs.vivaldi-ffmpeg-codecs  chromium-codecs-ffmpeg
nixpkgs.chromium-xorg-conf     chromium-xorg-conf
```

**Comment by guibou** [comment]
Thank you for this report.

There is two issues:

- The one with `nix-env -qaP 'nixgl.*'`, I don't understand that one at all.
- The one with `nix-env -u`, that one is due to a `null` value in the nvidia version. It means that your env do have one of the nvidia package, but the "auto-detection" of the version is not able to find your GPU. This can be improved a bit, however I'm wondering why you have a nixgl nvidia package installed without nvidia gpu (or you do have an nvidia GPU and there is something else weird that I do not understand).

**Comment by jkatzmewing** [comment]
Thanks for responding @guibou.

The `nix-env -qaP` one was just to demonstrate that querying is broken, if that's what you're asking? It looks like the same issue to me, but then I'm very new to nix.

Re the `null` value in the nvidia version, that's the thing - I _didn't_ have the nvidia version installed, only nixGLIntel and nixVulkanIntel.

**Comment by marrs** [comment]
I have a similar issue.  In my case I installed the `nixgl.nixGLDefault` package as recommended before I noticed the error.

> however I'm wondering why you have a nixgl nvidia package installed without nvidia gpu

I'd guess that whatever tries to detect the GPU doesn't work properly. ;)

I've tried uninstalling the package `nix-env --uninstall nixgl.nixGLDefault` but this doesn't seem to do anything (although running the command doesn't fail).

**Comment by vlnk** [comment]
Same issue here. It seems that the line [`cp /proc/driver/nvidia/version $out || touch $out`](https://github.com/guibou/nixGL/blob/master/nixGL.nix#L38) failed and doesn't result to `null` as expected if there is no nvidia gpu. Is there a way to check the existance of `/proc/driver/nvidia/version` before doing this operation.

**Comment by guibou** [comment]
I'm really sorry, Really. Life got a bit exiting theses days and I forgot to read my Github notifications.

I've pushed a PR #74 which should fix both issues. I've tested the different behaviors you described with `nix-env` and it works. Hopefully I did not break `nvidia` setup. If someone with `NVIDIA` is motivated to check, it will be appreciated.

**Comment by vlnk** [comment]
hi, thank you for your fix!

But, I have an issue when I try to test your branch `unknown_nvidia_version`, it seems that the documented way to install a wrapper is not working:

```
git clone https://github.com/guibou/nixGL
cd nixGL
git checkout unknown_nvidia_version
nix-env -f ./ -iA nixGLDefault
```

I feel I am missing something but if your are changing the way to install the wrappers from source, you should update the README.

**Comment by guibou** [comment]
You are perfectly right, sorry, my fix is half backed ;(

Let's go to the drawing board again.

**Comment by guibou** [comment]
PR #76 is updated, with a huge refactoring. Documentation is updated accordingly. Tell me if that's work for you.

**Comment by marrs** [comment]
I'm not quite sure how to test this.  I wasn't able to add the branch using `nix-channel` so I'm not able to establish if `nix-env -u` will now work.  I did manually install and test your latest version of the wrapper using the same procedure that @vlnk used and the wrapper is working fine for me, but then it was working for me before.

**Comment by Pipeline79** [comment]
This still doesn't work right for me.  My laptop is intel graphics only, and I only install that package.  The app works for me now, but if I do a channel update:

```
these derivations will be built:
  /nix/store/x9rw4lqnaxjb8cj6xisnhiff347y1siz-nixgl.drv
building '/nix/store/x9rw4lqnaxjb8cj6xisnhiff347y1siz-nixgl.drv'...
unpacking channels...
created 2 symlinks in user environment
```

Which breaks $ nix-env -qa in the manner described above.
I installed from source using the unknown_nvidia_version branch.

**Comment by guibou** [comment]
That's merged, we'll see how it goes in the future. Thank you for the report / discussion.
