### ISSUE TITLE
Doesn't work on Nix 2.0

### ISSUE THREAD

**Issue by Infinisil** [guibou/nixGL#9]
The `sha256 = null` trick doesn't work anymore in Nix 2.0, so upon trying to build the nvidia drivers, you'll get the following error:

```
these derivations will be built:
  /nix/store/p9vj7v4a3z9s3ma5shvjlbgiqgncr7wd-NVIDIA-Linux-x86_64-390.48.run.drv
  /nix/store/44gjnsclalq0k5l4pfjmh076qjiw9c3g-nvidia-390.48.drv
  /nix/store/p1vkygcw1nc0vx3xb5s9d02j52chbcqm-nixGLNvidia-1.0.0.drv
building '/nix/store/p9vj7v4a3z9s3ma5shvjlbgiqgncr7wd-NVIDIA-Linux-x86_64-390.48.run.drv'...
error checking the existence of http://tarballs.nixos.org/sha256/:
curl: (6) Could not resolve host: tarballs.nixos.org
trying http://download.nvidia.com/XFree86/Linux-x86_64/390.48/NVIDIA-Linux-x86_64-390.48.run
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: download.nvidia.com
error: cannot download NVIDIA-Linux-x86_64-390.48.run from any mirror
builder for '/nix/store/p9vj7v4a3z9s3ma5shvjlbgiqgncr7wd-NVIDIA-Linux-x86_64-390.48.run.drv' failed with exit code 1
cannot build derivation '/nix/store/44gjnsclalq0k5l4pfjmh076qjiw9c3g-nvidia-390.48.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/p1vkygcw1nc0vx3xb5s9d02j52chbcqm-nixGLNvidia-1.0.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/p1vkygcw1nc0vx3xb5s9d02j52chbcqm-nixGLNvidia-1.0.0.drv' failed
```

Replacing the null with the correct hash makes it work.

**Comment by guibou** [comment]
That's unfortunate, because it means that we need an array of all possible nvidia drivers and there hash. Or a wrapper script which prefetch the file AND then call `nix-build`.

I'll give a try to a solution like that tomorrow, thank you for reporting.

**Comment by guibou** [comment]
I tested today and it works on nix 2.0 without any issue, using `nixpkgs-unstable`. You log appears to be a simple network issue, and I bet that changing the hash solved the issue just because the network was fixed during that time.

Could you try again with `hash = null` and a working network ?

**Comment by Infinisil** [comment]
Nope that doesn't work, I should've been clearer: I tested my network along this, which was just fine, everything worked. The reason it appears to be a network issue is because according to @cleverca22 Nix detects that it's not a fixed-output derivation, so it doesn't give you network access to begin with.

**Comment by guibou** [comment]
Do you use sandboxing?

**Comment by Infinisil** [comment]
Indeed I do

**Comment by guibou** [comment]
Have a look at the script `nvidiaInstall` I just pushed, it fixes the issue.

Sorry it tooks a bit of discussion for me to understand the issue, I'm not using sandboxing on the distribution on which I'm using `nixGL` (arch linux) because sandboxing does not work on arch, so I was not aware of the issue.

Thank you for reporting.
