### ISSUE TITLE
`name` of `nvidiaDrivers` and `nvidiaLibsOnly` is wrong

### ISSUE THREAD

**Issue by jian-lin** [guibou/nixGL#92]
`linuxPackages.nvidia_x11` doesn't use `pname`, instead it [sets](https://github.com/NixOS/nixpkgs/blob/58526c2229a3866dc57b2006a848b61f3584cef3/pkgs/os-specific/linux/nvidia-x11/generic.nix#L50) `name = "nvidia-x11-${version}${nameSuffix}";`.

However, we only [set](https://github.com/guibou/nixGL/blob/17658df1e17a64bc23ee5c93cfa9e8b663a4ac81/nixGL.nix#L47-L48) `pname` and `version` in our `overrideAttrs`, which doesn't change the original `name`.

Do we need to keep the same name structure with `linuxPackages.nvidia_x11`?
If so, the fix for `nvidiaLibsOnly` is simple. But it's not simple to fix `nvidiaDrivers`, since it contains `nameSuffix`, which is defined by `nameSuffix = optionalString (!libsOnly) "-${kernel.version}";`.

**Comment by guibou** [comment]
Hello,

Thank you for opening this ticket.

I just override the `name` to `"nvidia-x11-${version}"` and I'm happy with that.

Please reopen if you would like another solution.
