### ISSUE TITLE
Nvidia icd file has now a disctinct name

### ISSUE THREAD

**Issue by leiserfg** [guibou/nixGL#93]
Running `nix-env -iA nixgl.auto.nixVulkanNvidia`   
returns
```
ls: cannot access '/nix/store/5ffhwa9kp5hay6ml0yk40vl8dj65gsmi-nvidia-x11-510.54/share/vulkan/icd.d/nvidia_icd.json': No such file or directory
```
The new name is `nvidia_icd.x86_64.json `

**Comment by guibou** [comment]
I added a test which build with `nvidia-x11-510` and it looks like it generate a wrapper script which points to the correct `icd` files. Could you test again and tell me if the bug is still there?

Thank you for opening the ticket by the way ;)

**Comment by seandheath** [comment]
@leiserfg would you mind providing an example of how to use the nvidiaVars you defined in a config.nix setup?

**Comment by leiserfg** [comment]
What I'm doing is just expose them in `home.sessionVariables` so every program runs with them set, it's impure I know but it's the less problematic way I've found.
